# Generated by Django 4.1 on 2022-11-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=10, verbose_name='이름')),
                ('client_phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('transaction_type', models.IntegerField(choices=[('1', '매매'), ('2', '전세'), ('3', '월세')], verbose_name='거래 종류')),
                ('property_type', models.IntegerField(choices=[('1', '아파트'), ('2', '빌라'), ('3', '상가'), ('4', '공장/창고'), ('5', '오피스텔'), ('6', '원룸')], verbose_name='부동산 종류')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='희망 지역')),
                ('price', models.IntegerField(default=0, verbose_name='매매가')),
                ('deposit', models.IntegerField(default=0, verbose_name='보증금')),
                ('monthly_rent', models.IntegerField(default=0, verbose_name='월세')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='비고')),
            ],
            options={
                'db_table': 'reception',
            },
        ),
    ]
