# Generated by Django 4.1 on 2022-11-15 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reception', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='state',
            field=models.IntegerField(choices=[('1', '접수'), ('2', '계약 중'), ('3', '계약 완료')], default=1, verbose_name='진행 단계'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reception_user', to=settings.AUTH_USER_MODEL, verbose_name='회원'),
        ),
    ]
