# Generated by Django 4.1 on 2022-11-15 12:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_reception_state_alter_reception_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='생성일'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reception',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='수정일'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='property_type',
            field=models.IntegerField(choices=[(1, '아파트'), (2, '빌라'), (3, '상가'), (4, '공장/창고'), (5, '오피스텔'), (6, '원룸')], verbose_name='부동산 종류'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='state',
            field=models.IntegerField(choices=[(1, '접수'), (2, '계약 중'), (3, '계약 완료')], default=1, verbose_name='진행 단계'),
        ),
        migrations.AlterField(
            model_name='reception',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, '매매'), (2, '전세'), (3, '월세')], verbose_name='거래 종류'),
        ),
    ]
