# Generated by Django 4.1 on 2022-08-07 16:30

from django.db import migrations, models
import user.models
import user.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(error_messages={'unique': '이미 사용 중인 이메일 입니다.'}, max_length=255, unique=True)),
                ('organization', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('userId', models.CharField(error_messages={'unique': '이미 사용 중인 아이디 입니다.'}, max_length=10, null=True, unique=True, validators=[user.validators.validate_no_special_characters])),
                ('name', models.CharField(max_length=10, null=True, validators=[user.validators.validate_no_special_characters])),
                ('phoneNumber', models.CharField(default='000-0000-0000', max_length=15, null=True, unique=True)),
                ('company', models.CharField(max_length=20)),
                ('ceoName', models.CharField(max_length=10)),
                ('businessNumber', models.IntegerField(blank=True, null=True)),
                ('businessRegistration', models.FileField(upload_to='')),
                ('businessStatus', models.CharField(max_length=30)),
                ('item', models.CharField(max_length=30)),
                ('officerNumber', models.IntegerField(blank=True, null=True)),
                ('officeCertificate', models.FileField(upload_to='')),
                ('address', models.CharField(max_length=40, null=True, validators=[user.validators.validate_no_special_characters])),
                ('faxNumber', models.IntegerField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'agency',
            },
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
