# Generated by Django 4.1 on 2022-08-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RealtyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='매물 종류')),
            ],
            options={
                'db_table': 'realty_type',
                'ordering': ['id'],
            },
        ),
    ]
