# Generated by Django 4.1 on 2022-11-15 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Realty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=10, verbose_name='소유자 성함')),
                ('client_phone', models.CharField(max_length=20, verbose_name='소유자 연락처')),
                ('phone_agency', models.IntegerField(choices=[('1', 'SKT'), ('2', 'KT'), ('3', 'LGU+'), ('4', 'SKT 알뜰폰'), ('5', 'KT 알뜰폰'), ('6', 'LGU+ 알뜰폰')], verbose_name='통신사')),
                ('lessee_phone', models.CharField(max_length=20, verbose_name='임차인 연락처')),
                ('transaction_type', models.IntegerField(choices=[('1', '매매'), ('2', '전세'), ('3', '월세')], verbose_name='거래 종류')),
                ('property_type', models.IntegerField(choices=[('1', '아파트'), ('2', '빌라'), ('3', '상가'), ('4', '공장/창고'), ('5', '오피스텔'), ('6', '원룸')], verbose_name='부동산 종류')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='지역')),
                ('price', models.IntegerField(default=0, verbose_name='매매가')),
                ('deposit', models.IntegerField(default=0, verbose_name='보증금')),
                ('monthly_rent', models.IntegerField(default=0, verbose_name='월세')),
                ('state', models.IntegerField(choices=[('1', '접수'), ('2', '계약 중'), ('3', '계약 완료')], default=1, verbose_name='진행 단계')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='비고')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='realty_user', to=settings.AUTH_USER_MODEL, verbose_name='회원')),
            ],
            options={
                'db_table': 'realty',
            },
        ),
    ]
