# Generated by Django 4.1.4 on 2022-12-13 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0003_realty_is_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, '매매'), (2, '전세'), (3, '월세'), (4, '연세')], verbose_name='거래 종류'),
        ),
    ]
