# Generated by Django 4.1 on 2022-12-30 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0005_alter_realty_phone_agency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realty',
            name='property_type',
            field=models.IntegerField(choices=[(1, '아파트'), (2, '빌라'), (3, '상가'), (4, '공장/창고'), (5, '오피스텔'), (6, '원룸')], null=True, verbose_name='부동산 종류'),
        ),
        migrations.AlterField(
            model_name='realty',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, '매매'), (2, '전세'), (3, '월세')], null=True, verbose_name='거래 종류'),
        ),
    ]
